language: ruby
rvm:
    - 2.1
    - 2.2
    - 2.3
    - ruby-2.4.0-preview2
    - ruby-head
sudo: required
before_install:
    - gem update --system
    - gem install bundler -v '~>1.13'
    - bundler --version
install:
    - make
    - gem build osp.gemspec
    - gem install osp-*.gem
    - gem list -l osp
script:
    - make test
    - cd
    - which -a osp
    - osp --version
